name: Download and Convert Video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install yt-dlp and ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install yt-dlp

    - name: Read video link
      id: read_link
      run: |
        LINK=$(cat video_link.txt)
        echo "link=$LINK" >> $GITHUB_ENV

    - name: Download video
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        yt-dlp "$link" -o "original_video_${TIMESTAMP}.mp4"
        echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV

    - name: Convert video to 720p
      run: |
        ffmpeg -i original_video_${TIMESTAMP}.mp4 -vf "scale=-1:720" -c:v libx264 -crf 23 -preset fast -c:a aac -b:a 128k video_720p_${TIMESTAMP}.mp4

    - name: Convert video to 480p
      run: |
        ffmpeg -i original_video_${TIMESTAMP}.mp4 -vf "scale=-1:480" -c:v libx264 -crf 23 -preset fast -c:a aac -b:a 128k video_480p_${TIMESTAMP}.mp4

    - name: Convert video to 360p
      run: |
        ffmpeg -i original_video_${TIMESTAMP}.mp4 -vf "scale=-1:360" -c:v libx264 -crf 23 -preset fast -c:a aac -b:a 128k video_360p_${TIMESTAMP}.mp4

    - name: Upload video files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: converted-videos-${{ steps.read_link.outputs.timestamp }}
        path: |
          video_720p_${TIMESTAMP}.mp4
          video_480p_${TIMESTAMP}.mp4
          video_360p_${TIMESTAMP}.mp4
